input {
  beats {
    port => 5050
  }
}

filter {
  if [fields][file_type] == "xml" {
    if [fields][type] == "app_config" {
        xml {
        source => "message"
        store_xml => false
        force_array => false
        remove_namespaces => true
        xpath => [
            "/app/name/text()", "app_name",
            "/app/version/text()", "app_version"
        ]
        }
        mutate {
            add_field => {
                "config_type" => "app_config"
                # "[config][app][name]" => "%{app_name}"
                # "[config][app][version]" => "%{app_version}"
            }
            rename => {
                "app_name[0]" => "[config][app][name]"
                "app_version[0]" => "[config][app][version]"
            }
        }
    }
    if [fields][type] == "app_db_config" {
            xml {
            source => "message"
            store_xml => false
            xpath => [
                "/datasources/datasource/name/text()", "datasource_name",
                "/datasources/datasource/url/text()", "db_url"
            ]
            }
            mutate {
                add_field => {
                    "config_type" => "datasource_config"
                    # "[config][db][name]" => "%{datasource_name}"
                    # "[config][db][url]" => "%{db_url}"
                }
                rename => {
                "datasource_name[0]" => "[config][db][name]"
                "db_url[0]" => "[config][db][url]"
            }
        }
    } 
  } else {
    drop { } # skip non-XML events
  }
}


output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "app-configs"
    document_id => "%{[host][name]}"
    action => "update"
    doc_as_upsert => true
  }
  #stdout { codec => rubydebug }
}