input {
  beats {
    port => 5050
  }
}

filter {
  if [fields][type] == "app_log" {
    mutate {
      add_field => { "type" => "app_log" }
      add_field => { "server" => "%{[host][name]}" }
      add_field => { "filename" => "%{[log][file][path]}" }
    }
  } else {
    drop { } # skip non-log events
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "logs-app-%{[host][name]}-%{+YYYY.MM.dd}"
    document_id => "%{[host][name]}-%{+YYYY.MM.dd}-%{[log][file][path]}"
  }
  #stdout { codec => rubydebug }
}
